lib/wttj_backend_test_web/router.ex
defmodule WttjBackendTestWeb.Router do
  use WttjBackendTestWeb, :router
  use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api/v1", WttjBackendTestWeb do
    pipe_through :api

    get "/offers/:offer_id", OfferController, :get_offer_by_id
    get "/professions/:profession_id", ProfessionController, :get_profession_by_id

    resources "/offers", OfferController
    resources "/professions", ProfessionController
  end

  # Other scopes may use custom stacks.
  # scope "/api", WttjBackendTestWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WttjBackendTestWeb.Telemetry
    end
  end

  defp handle_errors(conn, %{reason: %Phoenix.Router.NoRouteError{message: message}}) do
    conn |> json(%{error: message}) |> halt()
  end

  defp handle_errors(conn, _) do
    conn |> json(%{error: "unknown"}) |> halt()
  end
end

lib/wttj_backend_test/job/offer.ex
defmodule WttjBackendTest.Job.Offer do
  use Ecto.Schema
  import Ecto.Changeset

  schema "offers" do
    field :contract_type, :string
    field :latitude, :float
    field :longitude, :float
    field :name, :string
    field :profession_id, :integer

    timestamps()
  end

  @doc false
  def changeset(offer, attrs) do
    offer
    |> cast(attrs, [:profession_id, :contract_type, :name, :latitude, :longitude])
    |> validate_required([:contract_type, :name])
  end
end

lib/wttj_backend_test_web/controllers/offer_controller.ex
defmodule WttjBackendTestWeb.OfferController do
  use WttjBackendTestWeb, :controller

  alias WttjBackendTest.Repo
  alias WttjBackendTest.Job.Offer

  import Ecto.Query
  import WttjBackendTest.RateLimit

  plug :rate_limit, max_requests: 5, interval_seconds: 60
  plug :action

  def index(conn, params) do
    limit = if params["limit"] do String.to_integer(params["limit"]) else 100 end
    offset = if params["offset"] do String.to_integer(params["offset"]) else 0 end
    direction = if params["direction"] == "asc" do :asc else :desc end
    order = if params["order"] do String.to_atom(params["order"]) else :id end

    offers = Offer
      |> filter_by_name(params["name"])
      |> filter_by_contract_type(params["contract_type"])
      |> filter_by_profession_id(params["profession_id"])
      |> order_by({^direction, ^order})
      |> offset(^offset)
      |> limit(^limit)
      |> Repo.all

    render conn, offers: offers
  end

  def get_offer_by_id(conn, %{"offer_id" => offer_id}) do
    offer = Repo.get_by(Offer, id: offer_id)
    render conn, offer: offer
  end

  defp filter_by_name(query, match) do
    where(query, [offer], ilike(offer.name, ^"%#{match}%"))
  end

  defp filter_by_contract_type(query, match) do
    where(query, [offer], ilike(offer.contract_type, ^"%#{match}%"))
  end

  defp filter_by_profession_id(query, match) do
    if is_nil(match) do
      query
    else
      where(query, [offer], offer.profession_id == ^match)
    end
  end
end

lib/wttj_backend_test_web/views/offer_view.ex
defmodule WttjBackendTestWeb.OfferView do
  use WttjBackendTestWeb, :view

  def render("index.json", %{offers: offers}) do
    offers
  end

  def render("get_offer_by_id.json", %{offer: offer}) do
    offer
  end
end

lib/wttj_backend_test_web/templates/offer/edit.html.eex
<h1>Edit Offer</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.offer_path(@conn, :update, @offer)) %>

<span><%= link "Back", to: Routes.offer_path(@conn, :index) %></span>

lib/wttj_backend_test_web/templates/offer/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :contract_type %>
  <%= text_input f, :contract_type %>
  <%= error_tag f, :contract_type %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :latitude %>
  <%= number_input f, :latitude, step: "any" %>
  <%= error_tag f, :latitude %>

  <%= label f, :longitude %>
  <%= number_input f, :longitude, step: "any" %>
  <%= error_tag f, :longitude %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/wttj_backend_test_web/templates/offer/index.html.eex
<h1>Listing Offers</h1>

<table>
  <thead>
    <tr>
      <th>Contract type</th>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for offer <- @offers do %>
    <tr>
      <td><%= offer.contract_type %></td>
      <td><%= offer.name %></td>
      <td><%= offer.latitude %></td>
      <td><%= offer.longitude %></td>

      <td>
        <span><%= link "Show", to: Routes.offer_path(@conn, :show, offer) %></span>
        <span><%= link "Edit", to: Routes.offer_path(@conn, :edit, offer) %></span>
        <span><%= link "Delete", to: Routes.offer_path(@conn, :delete, offer), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Offer", to: Routes.offer_path(@conn, :new) %></span>

lib/wttj_backend_test_web/templates/offer/new.html.eex
<h1>New Offer</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.offer_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.offer_path(@conn, :index) %></span>

lib/wttj_backend_test_web/templates/offer/show.html.eex
<h1>Show Offer</h1>

<ul>

  <li>
    <strong>Contract type:</strong>
    <%= @offer.contract_type %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @offer.name %>
  </li>

  <li>
    <strong>Latitude:</strong>
    <%= @offer.latitude %>
  </li>

  <li>
    <strong>Longitude:</strong>
    <%= @offer.longitude %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.offer_path(@conn, :edit, @offer) %></span>
<span><%= link "Back", to: Routes.offer_path(@conn, :index) %></span>