lib/wttj_backend_test_web/router.ex
defmodule WttjBackendTestWeb.Router do
  use WttjBackendTestWeb, :router
  use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api/v1", WttjBackendTestWeb do
    pipe_through :api

    get "/offers/:offer_id", OfferController, :get_offer_by_id
    get "/professions/:profession_id", ProfessionController, :get_profession_by_id

    resources "/offers", OfferController
    resources "/professions", ProfessionController
  end

  # Other scopes may use custom stacks.
  # scope "/api", WttjBackendTestWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WttjBackendTestWeb.Telemetry
    end
  end

  defp handle_errors(conn, %{reason: %Phoenix.Router.NoRouteError{message: message}}) do
    conn |> json(%{error: message}) |> halt()
  end

  defp handle_errors(conn, _) do
    conn |> json(%{error: "unknown"}) |> halt()
  end
end

lib/wttj_backend_test/job/profession.ex
defmodule WttjBackendTest.Job.Profession do
  use Ecto.Schema
  import Ecto.Changeset

  schema "professions" do
    field :category_name, :string
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(profession, attrs) do
    profession
    |> cast(attrs, [:name, :category_name])
    |> validate_required([:name, :category_name])
  end
end

lib/wttj_backend_test_web/controllers/profession_controller.ex
defmodule WttjBackendTestWeb.ProfessionController do
  use WttjBackendTestWeb, :controller

  alias WttjBackendTest.Repo
  alias WttjBackendTest.Job.Profession

  import Ecto.Query
  import WttjBackendTest.RateLimit

  plug :rate_limit, max_requests: 5, interval_seconds: 60
  plug :action

  def index(conn, params) do
    limit = if params["limit"] do String.to_integer(params["limit"]) else 100 end
    offset = if params["offset"] do String.to_integer(params["offset"]) else 0 end
    direction = if params["direction"] == "asc" do :asc else :desc end
    order = if params["order"] do String.to_atom(params["order"]) else :id end

    professions = Profession
      |> filter_by_name(params["name"])
      |> filter_by_category_name(params["category_name"])
      |> order_by({^direction, ^order})
      |> offset(^offset)
      |> limit(^limit)
      |> Repo.all

    render conn, professions: professions
  end

  def get_profession_by_id(conn, %{"profession_id" => profession_id}) do
    profession = Repo.get_by(Profession, id: profession_id)
    render conn, profession: profession
  end

  defp filter_by_name(query, match) do
    where(query, [profession], ilike(profession.name, ^"%#{match}%"))
  end

  defp filter_by_category_name(query, match) do
    where(query, [profession], ilike(profession.category_name, ^"%#{match}%"))
  end
end

lib/wttj_backend_test_web/views/profession_view.ex
defmodule WttjBackendTestWeb.ProfessionView do
  use WttjBackendTestWeb, :view

  def render("index.json", %{professions: professions}) do
    professions
  end

  def render("get_profession_by_id.json", %{profession: profession}) do
    profession
  end
end

lib/wttj_backend_test_web/templates/profession/edit.html.eex
<h1>Edit Profession</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.profession_path(@conn, :update, @profession)) %>

<span><%= link "Back", to: Routes.profession_path(@conn, :index) %></span>

lib/wttj_backend_test_web/templates/profession/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :category_name %>
  <%= text_input f, :category_name %>
  <%= error_tag f, :category_name %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/wttj_backend_test_web/templates/profession/index.html.eex
<h1>Listing Professions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for profession <- @professions do %>
    <tr>
      <td><%= profession.name %></td>
      <td><%= profession.category_name %></td>

      <td>
        <span><%= link "Show", to: Routes.profession_path(@conn, :show, profession) %></span>
        <span><%= link "Edit", to: Routes.profession_path(@conn, :edit, profession) %></span>
        <span><%= link "Delete", to: Routes.profession_path(@conn, :delete, profession), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Profession", to: Routes.profession_path(@conn, :new) %></span>

lib/wttj_backend_test_web/templates/profession/new.html.eex
<h1>New Profession</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.profession_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.profession_path(@conn, :index) %></span>

lib/wttj_backend_test_web/templates/profession/show.html.eex
<h1>Show Profession</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @profession.name %>
  </li>

  <li>
    <strong>Category name:</strong>
    <%= @profession.category_name %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.profession_path(@conn, :edit, @profession) %></span>
<span><%= link "Back", to: Routes.profession_path(@conn, :index) %></span>